# Generated by Django 2.1.7 on 2019-03-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190331_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Party'),
        ),
    ]
