# Generated by Django 2.1.7 on 2019-03-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190331_1852'),
        ('group', '0003_auto_20190331_1820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'admin_id')},
        ),
    ]
