# Generated by Django 2.1.7 on 2019-03-30 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
