# Generated by Django 2.1.7 on 2019-03-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190331_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Usertype'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Usertype'),
        ),
    ]
